### ISSUE TITLE
倉庫名を命令を使って小文字に

### ISSUE THREAD

**Issue by cmplstofB** [cmplstofB/docker-package-test#1]
```yaml
${{ github.repository }}
```
とかで倉庫名が取得できる[ref]けれども，
このままだとDockerの標識に指定する際に
大文字が含まれてしまい，怒られる。

どうにかして小文字に変換したい。
GitHub Actionsで`runs-on: ubuntu-latest`を指定した場合だとBashが既定の仕類だそうだから[ref]
こいつの変数演算を使って，
* 倉庫名を変数に格納
* その変数を小文字に変換
という手筈で実現できないだろうか。

**Comment by cmplstofB** [comment]
`output`を利用してもいいかも
```yaml
    outputs:
      usr_rep: 
    steps:
    - id: set-matrix
      run: echo "::set-output name=usr_rep::XXX"
```
みたいな。
（[参考](https://docs.github.com/ja/actions/reference/context-and-expression-syntax-for-github-actions#%E3%82%B5%E3%83%B3%E3%83%97%E3%83%AB-6)）
