### ISSUE TITLE
自動更新

### ISSUE THREAD

**Issue by cmplstofB** [cmplstofB/docker-package-test#2]
Alpine LinuxやTeX Liveの更新を感知して，
またはそう高級でなくてもいいから
一定間隔で，
本倉庫を自動更新する。

これは手許の計算機で`cron`などを用いれば
実現できるが，
それでは結局負担がほとんど軽減しない
（手許の計算機を管理しなくてはいけない）
ので，GitHub上で完結したい。
しかし，そもそも可能なのか不明。

**Comment by cmplstofB** [comment]
```yaml
on:
  schedule:
    # * はYAMLに置ける特殊文字なので、この文字列は引用符で囲まなければならない
    - cron:  '*/15 * * * *'
```

from: https://docs.github.com/ja/actions/reference/events-that-trigger-workflows

これはどうだ？
